language: node_js
node_js:
  - "node"
install:
  - "yarn install"
script:
  - "yarn run build"
cache: yarn
deploy:
  provider: pages
  skip-cleanup: true
  github-token: GITHUB_TOKEN_1  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  target-branch: gh-pages
  on:
    branches:
      only:
        - master